import {initCalendar} from "./calendar.js";
import {initViewSelect} from "./view-select.js";
import { initEventCreateButtons } from "./event-create-button.js";
import {initEventDetailsDialog} from "./event-details-dialog.js";
import {initEventFormDialog} from "./event-form-dialog.js";
import {initNotifications} from "./notifications.js";
import {initEventStore} from "./event-store.js";
import {initNav} from "./nav.js";
import {initEventDeleteDialog} from "./event-delete-dialog.js";
import {initMiniCalendars} from "./mini-calendar.js"; 
import {initResponsive} from "./responsive.js";
import {initMobileSidebar} from "./mobile-sidebar.js";
import {initHamburger} from "./hamburger.js";
import {initUrl} from "./url.js";
import { initSync } from "./sync.js";
import { initSidebarChartToggle } from './sidebar-chart-toggle.js';


initViewSelect();
initEventCreateButtons();
initEventFormDialog(); 
initNotifications();
const eventStore = initEventStore();
initCalendar(eventStore);
initNav();
initEventDetailsDialog();
initEventDeleteDialog();
initMiniCalendars();
initResponsive();
initMobileSidebar();  
initHamburger();
initUrl();
initSync();
initSidebarChartToggle();